version: "3.3"
services:
  web:
    build:
      context: .
      args:
        TAG: jp01
    container_name: jobportal-app-container
    image: sumitchavan01/my-jobportal-app:jp01
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
